version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: depgraph-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: depgraph
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: depgraph-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-data:
